In [ ]:
pip install folium

In [ ]:
import folium
import pandas as pd

data = pd.read_csv('C:/Users/MSI/Desktop/detectors2018.csv')
latitude = data.iloc[:, 5].astype(str).apply(lambda x: float(x[:2] + '.' + x[2:]))
longitude = data.iloc[:, 6].astype(str).apply(lambda x: float(x[:4] + '.' + x[4:]))
ids = data.iloc[:, 1]

map = folium.Map(location=[latitude.mean(), longitude.mean()], zoom_start=10)

for lat, lon, id in zip(latitude, longitude, ids):
    folium.CircleMarker(location=[lat, lon], radius=5, color='blue', fill=True, fill_color='blue',
                        tooltip=id).add_to(map)

map

In [36]:
map.save('C:/Users/MSI/Desktop/NDEX_2018_map.html')

In [ ]:
pip install geopy

In [39]:
import pandas as pd
from geopy.distance import great_circle
import numpy as np

data = pd.read_csv('C:/Users/MSI/Desktop/detectors2018.csv')

latitude = data.iloc[:, 5].astype(str).apply(lambda x: float(x[:2] + '.' + x[2:]))
longitude = data.iloc[:, 6].astype(str).apply(lambda x: float(x[:4] + '.' + x[4:]))
ids = data.iloc[:, 1]

num_nodes = len(latitude)
adj_matrix = np.zeros((num_nodes, num_nodes))

min_distance = 0.1  
max_distance = 10.0  

for i in range(num_nodes):
    for j in range(i + 1, num_nodes):
       
        loc1 = (latitude.iloc[i], longitude.iloc[i])
        loc2 = (latitude.iloc[j], longitude.iloc[j])
        distance = great_circle(loc1, loc2).kilometers

        # Check if distance is within the specified range
        if distance >= min_distance and distance <= max_distance:
            # Add edge to adjacency matrix
            adj_matrix[i, j] = 1
            adj_matrix[j, i] = 1

# Print adjacency matrix
print(adj_matrix)


[[0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
